### ISSUE TITLE
Error using visualize_attention.py. The size of tensor a (3234) must match the size of tensor b (3181) at non-singleton dimension 1

### ISSUE THREAD

**Issue by cishwarya** [facebookresearch/dino#19] opened 2021-05-04 12:33 UTC
Hi all, I am trying to execute visualize_attention.py with default pretrained weights on my own image as below

`!python visualize_attention.py --image_path 'test/finalImg_249.png'`

I get size mistamatch error. Could you please let me know what changes needs to be done here?

**Error stack trace:**

Please use the `--pretrained_weights` argument to indicate the path of the checkpoint to evaluate.
Since no pretrained weights have been provided, we load the reference pretrained DINO weights.
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3458: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.

  "See the documentation of nn.Upsample for details.".format(mode)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  "The default behavior for interpolate/upsample with float scale_factor changed "

Traceback (most recent call last):
  File "visualize_attention.py", line 162, in <module>
    attentions = model.forward_selfattention(img.to(device))
  File "~/dino/vision_transformer.py", line 246, in forward_selfattention
    x = x + pos_embed

**RuntimeError: The size of tensor a (3234) must match the size of tensor b (3181) at non-singleton dimension 1**

**Image details:**
import cv2
img = cv2.imread('finalImg_249.png')
print (img.shape) #output: (427, 488, 3)

**Comment by user1234554321** [comment] 2021-05-04 12:48
Can you please give more information like size of image, the line on which the error occurred (or the error stack trace).

**Comment by woctezuma** [comment] 2021-05-04 12:54
The size of image would be interesting. Is it square for instance?

**Comment by cishwarya** [comment] 2021-05-04 15:32
> Can you please give more information like size of image, the line on which the error occurred (or the error stack trace).

Dear @user1234554321 I have updated the error stack trace and image details in the comment. Please let me know if you require any further details.

**Comment by cishwarya** [comment] 2021-05-04 15:35
> What happens with the default parameters? Try to run:
> 
> ```shell
> !python visualize_attention.py
> ```
> 
> This is the default image (480x480 PNG): https://dl.fbaipublicfiles.com/dino/img.png
> 
> ![Default](https://camo.githubusercontent.com/c6c421c461cf466a20800f3d1f67624559aaeb271e007951d0cfa6e59262adc6/68747470733a2f2f646c2e666261697075626c696366696c65732e636f6d2f64696e6f2f696d672e706e67)
> 
> Do you see any obvious difference with yours?

Dear @woctezuma when I run the below cmd without any params it works.  My image is originally gray scale which I have converted to 3 channels. image shape is (427, 488, 3). Is there any restriction with the image?. Does it have to be sqaure?
!python visualize_attention.py


**output:**

Please use the `--pretrained_weights` argument to indicate the path of the checkpoint to evaluate.
Since no pretrained weights have been provided, we load the reference pretrained DINO weights.
Please use the `--image_path` argument to indicate the path of the image you wish to visualize.
Since no image path have been provided, we take the first image in our paper.
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3458: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  "The default behavior for interpolate/upsample with float scale_factor changed "
./attn-head0.png saved.
./attn-head1.png saved.
./attn-head2.png saved.
./attn-head3.png saved.
./attn-head4.png saved.
./attn-head5.png saved.
./mask_th0.6_head0.png saved.
./mask_th0.6_head1.png saved.
./mask_th0.6_head2.png saved.
./mask_th0.6_head3.png saved.
./mask_th0.6_head4.png saved.
./mask_th0.6_head5.png saved.

**Comment by user1234554321** [comment] 2021-05-04 17:30
Hmm, have tried an image with same shape, but not able to reproduce the error. Can you tell your torch and torchvision versions.
Had guessed that the particular line maybe where it is happening, but not clear why. If I write a print statement to get the shapes of `x` and `pos_embed` like this (in the vision_transformer file)
`
print(x.shape, pos_embed.shape, 'x and pos_embed shapes')
x = x + pos_embed # see line 246
`
I get this
`torch.Size([1, 3234, 384]) torch.Size([1, 3234, 384]) x and pos_embed shapes`
which means for me pos_embed has the correct shape of 3234 `(427 // 8* 488 // 8 + 1)` but something is amiss in your env.

Can you please replace the `forward_selfattention` function in `vision_transformer` file with this to check shapes at each step:


    def forward_selfattention(self, x):        
        B, nc, w, h = x.shape
        N = self.pos_embed.shape[1] - 1
        print(B, nc, w, h, 'B, nc, w, and h')
        x = self.patch_embed(x)
        print(x.shape, 'x shape')
        # interpolate patch embeddings
        dim = x.shape[-1]
        w0 = w // self.patch_embed.patch_size
        h0 = h // self.patch_embed.patch_size
        print(self.pos_embed.shape, 'pos_embed.shape')
        class_pos_embed = self.pos_embed[:, 0]
        patch_pos_embed = self.pos_embed[:, 1:]
        print(class_pos_embed.shape, patch_pos_embed.shape, 'class_pos_embed and patch_pos_embed shapes')
        patch_pos_embed = nn.functional.interpolate(
            patch_pos_embed.reshape(1, int(math.sqrt(N)), int(math.sqrt(N)), dim).permute(0, 3, 1, 2),
            scale_factor=(w0 / math.sqrt(N), h0 / math.sqrt(N)),
            mode='bicubic',
        )
        print(w0, w, h0, h, patch_pos_embed.shape, 'w0, w, h0, h and patch_pos_embed shapes')
        if w0 != patch_pos_embed.shape[-2]:
            helper = torch.zeros(h0)[None, None, None, :].repeat(1, dim, w0 - patch_pos_embed.shape[-2], 1).to(x.device)
            patch_pos_embed = torch.cat((patch_pos_embed, helper), dim=-2)
        if h0 != patch_pos_embed.shape[-1]:
            helper = torch.zeros(w0)[None, None, :, None].repeat(1, dim, 1, h0 - patch_pos_embed.shape[-1]).to(x.device)
            pos_embed = torch.cat((patch_pos_embed, helper), dim=-1)
        patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1).view(1, -1, dim)
        pos_embed = torch.cat((class_pos_embed.unsqueeze(0), patch_pos_embed), dim=1)
        cls_tokens = self.cls_token.expand(B, -1, -1)
        x = torch.cat((cls_tokens, x), dim=1)
        print(x.shape, pos_embed.shape, 'x and pos_embed shapes')
        x = x + pos_embed
        x = self.pos_drop(x)
        for i, blk in enumerate(self.blocks):
            if i < len(self.blocks) - 1:
                x = blk(x)
            else:
                return blk(x, return_attention=True)

**Comment by woctezuma** [comment] 2021-05-04 18:04
My blind guess is that the issue comes from the fact that the image is grayscale.

**Comment by user1234554321** [comment] 2021-05-04 18:08
Don't think so it is because of grey. Have tried with grey. 

    elif os.path.isfile(args.image_path):
        with open(args.image_path, 'rb') as f:
            img = Image.open(f)
            img = img.convert('RGB')

this converts to RGB even if grey in the `visualize_attention` file I think.

**Comment by woctezuma** [comment] 2021-05-04 18:11
True.

Can the problematic image be shared?

Otherwise, I can create a dummy one.

**Comment by woctezuma** [comment] 2021-05-04 18:21
I have tested this on Colab, and it is fine:
```bash
%cd /content/
!git clone https://github.com/facebookresearch/dino.git
%cd /content/dino/
!wget https://i.imgur.com/MzHsAPj.png
!python visualize_attention.py --image_path MzHsAPj.png
```

**Comment by user1234554321** [comment] 2021-05-04 18:23
This could be the issue
https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/vision_transformer.py#L238-L240
h
Here it is `pos_embed`
while in the previous case
https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/vision_transformer.py#L235-L237
it is `patch_pos_embed`

**Comment by woctezuma** [comment] 2021-05-04 18:24
Ah! The issue can be reproduced with the rotated image!

```bash
!wget https://i.imgur.com/EewJtZU.png
!python visualize_attention.py --image_path EewJtZU.png
```

**Comment by user1234554321** [comment] 2021-05-04 18:25
Yes, it happens on one side because they have introduced a new variable `pos_embed` I think.

**Comment by woctezuma** [comment] 2021-05-04 18:29
True.

https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/vision_transformer.py#L245-L246

vs.

https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/vision_transformer.py#L191-L192

and

https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/vision_transformer.py#L261-L262

**Comment by cishwarya** [comment] 2021-05-04 19:32
@woctezuma @user1234554321 thanks so much for your reply. PFA the image. The issue still exists.
![finalImg_249](https://user-images.githubusercontent.com/616016/117059531-308c6c80-ad20-11eb-9fd9-111d21e0b532.png)

**Comment by user1234554321** [comment] 2021-05-04 19:44
Hi, can you resize the image using

img = cv2.imread('finalImg_249.png')   
img2 = cv2.resize(img, (480, 427))   
cv2.imwrite('finalImg_249_2.png', img2)   

and try.

**Comment by cishwarya** [comment] 2021-05-04 19:57
Hi @user1234554321 after resizing from (427, 488, 3)) -> (427, 480, 3) as you suggested above, it does work :) Hurray !!!! . Could you please briefly explain what was causing the issue and in future what image dimension would you suggest to use ?
Also I have a bunch of such greyscale images and wanted to train from scratch with Dino . In this case, could you please let me know what steps should I follow to do the training? thanks again

**Comment by user1234554321** [comment] 2021-05-04 20:03
> Yes, it happens on one side because they have introduced a new variable `pos_embed` I think.
> 
> https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/vision_transformer.py#L235-L246
> 
> Here the `patch_pos_embed` needs to get padded to move from height `60` to `61` but instead of padding `patch_pos_embed`, it is assigned to `pos_embed` and therein lies the problem I believe.
> Since, `patch_pos_embed` shape remains `1x384x53x60` instead of `1x384x53x61` (batch, dim, patches_in_width, patches_in_height), after flatten and transpose, we get `patch_pos_embed` shape as `1x3180x384` (60 * 53 = 3180).
> After concatenating the `class_pos_embed`, we get the shape as `1x3181x384`.
> However, if it were padded properly, we would go from `1x384x53x61` to `1x3233x384` to `1x3234x384` which is the required shape for adding to `x`.

I have explained here. It's probably a typo in the variable name. Have to clarify from the authors.
I am training greyscale images as well, will let you know how it goes!

**Comment by cishwarya** [comment] 2021-05-04 20:28
@user1234554321 thank you for your reply and please do let me know once you are done training greyscale images.

**Comment by mathildecaron31** [comment] 2021-05-05 09:57
Hi all, yes that's definitely a typo...

**Comment by mathildecaron31** [comment] 2021-05-05 10:44
I am closing the issue. Feel free to reopen if needed.

**Closed by mathildecaron31** 2021-05-05 10:44 UTC
